server:
  port: 8014
  
spring:    
  application:
    name: studentservice  
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
  
#management:
#  security:
#    enabled: false  
 
logging:
  level:
    com.self.sprintboot.learning.company: DEBUG