server:
  port: 8011    #port number
 
spring:    
  application:
    name: _03_company-service   
     
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
     
#management:
#  security:
#    enabled: false  

logging:
  level:
    company:
      service: DEBUG